development:
  sessions:
    default:
      database: gramophone_development
      hosts:
        - 127.0.0.1:27017
  options:
    raise_not_found_error: false
    use_utc: true

test:
  sessions:
    default:
      database: gramophone_test
      hosts:
        - 127.0.0.1:27017
        - 127.0.0.1:27017
  options:
    raise_not_found_error: false
    use_utc: true

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URI'] || ENV['MONGOLAB_URI'] %>
  options:
    raise_not_found_error: false
    use_utc: true
